# Generated by Django 5.1 on 2024-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('profilePic', models.URLField(default='/media/default_avatars/default_00.jpg')),
                ('account_creation', models.DateTimeField(auto_now_add=True)),
                ('last_seen_online', models.DateTimeField(null=True)),
                ('single_games_pong_won', models.IntegerField(default=0)),
                ('single_games_pong_lost', models.IntegerField(default=0)),
                ('single_games_c4_won', models.IntegerField(default=0)),
                ('single_games_c4_lost', models.IntegerField(default=0)),
                ('tournaments_pong_won', models.IntegerField(default=0)),
                ('tournaments_pong_lost', models.IntegerField(default=0)),
                ('tournaments_c4_won', models.IntegerField(default=0)),
                ('tournaments_c4_lost', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(blank=True, to='users_app.publicuser')),
            ],
        ),
    ]
