# Generated by Django 5.1 on 2024-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='single_game_lost',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='single_game_won',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='tounament_won',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='tournament_game_lost',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='tournament_game_won',
        ),
        migrations.RemoveField(
            model_name='publicuser',
            name='tournament_lost',
        ),
        migrations.AddField(
            model_name='publicuser',
            name='single_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='single_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='tounaments_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='tournament_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='tournament_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='tournaments_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicuser',
            name='last_seen_online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
