# Generated by Django 5.1 on 2024-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.URLField(default='/media/default_avatars/default_00.jpg'),
        ),
    ]
