# Generated by Django 5.1 on 2024-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_remove_publicuser_single_game_lost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='tounaments_won',
        ),
        migrations.AddField(
            model_name='publicuser',
            name='tournaments_won',
            field=models.IntegerField(default=0),
        ),
    ]
