# Generated by Django 5.1 on 2024-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_publicuser_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.URLField(default='http://localhost:8080/media/default.jpg'),
        ),
    ]
