# Generated by Django 5.1 on 2024-10-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_publicuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.URLField(default='http://localhost:8080/media/default_avatars/default_00.jpg'),
        ),
    ]
