# Generated by Django 5.1 on 2024-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='9d6bc582-74a9-4e28-9a38-3126eb498897', max_length=100, unique=True),
        ),
    ]
