# Generated by Django 5.1 on 2024-10-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0002_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='6987ca6f-b5cf-4a7e-9e60-a09cdd6de4e3', max_length=100, unique=True),
        ),
    ]
