# Generated by Django 5.1 on 2024-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0003_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='a6a491cf-74b2-4b08-b92c-07787412c45e', max_length=100, unique=True),
        ),
    ]
