# Generated by Django 5.1 on 2024-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0004_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='1b1b4a9c-af77-4838-9834-264fde28dd47', max_length=100, unique=True),
        ),
    ]
