# Generated by Django 5.1 on 2024-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0005_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='d7a01ede-7fc1-4c1e-925f-5e18771aaabc', max_length=100, unique=True),
        ),
    ]
