# Generated by Django 5.1 on 2024-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0006_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='c8d7db1b-4b3f-45a7-978d-9c4290bbd744', max_length=100, unique=True),
        ),
    ]
