# Generated by Django 5.1 on 2024-10-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0007_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='36a85cb1-d370-483d-a530-cadb30ecbbc4', max_length=100, unique=True),
        ),
    ]
