# Generated by Django 5.1 on 2024-10-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0008_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='b0dc19e8-8d0d-4d21-8868-f5c97b369f28', max_length=100, unique=True),
        ),
    ]
