# Generated by Django 5.1 on 2024-10-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0009_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='775de97e-095f-4672-92c0-ad7be70ae9a2', max_length=100, unique=True),
        ),
    ]
