# Generated by Django 5.1 on 2024-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0010_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
