# Generated by Django 5.1 on 2024-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0011_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotegame',
            name='id',
        ),
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='<function uuid4 at 0x7f03ab6e7b00>', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
