# Generated by Django 5.1 on 2024-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_remote_app', '0012_remove_remotegame_id_alter_remotegame_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotegame',
            name='game_id',
            field=models.CharField(default='da436cd1-4bf1-4ea1-924d-1cecdfe25c58', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
