# Generated by Django 5.1 on 2024-10-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_local_app', '0002_delete_remotegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localgame',
            name='game_creator',
        ),
    ]
