# Generated by Django 5.1 on 2024-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentuser',
            name='user_profile',
            field=models.CharField(null=True),
        ),
    ]
