# Generated by Django 5.1 on 2024-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0002_alter_tournamentuser_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentuser',
            name='user_profile',
            field=models.CharField(null=True),
        ),
    ]
