# Generated by Django 5.1 on 2024-10-31 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inqueueuser',
            name='last_range_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
