# Generated by Django 5.1 on 2024-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_schedule',
            field=models.JSONField(null=True),
        ),
    ]
