# Generated by Django 5.1 on 2024-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.TextField(choices=[('pong', 'Pong'), ('c4', 'Connect four')]),
        ),
    ]
