# Generated by Django 5.1 on 2024-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0002_match_round_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round_schedule',
        ),
        migrations.AddField(
            model_name='tournament',
            name='round_schedule',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('in_progress', 'In progress')], default='pending', max_length=20),
        ),
    ]
