# Generated by Django 5.1 on 2024-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0002_match_tournament_alter_match_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.TextField(choices=[('pong', 'Pong'), ('connect_four', 'Connect four')]),
        ),
    ]
