# Generated by Django 5.1 on 2024-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0003_alter_match_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchuser',
            name='last_online_update',
            field=models.DateTimeField(null=True),
        ),
    ]
