# Generated by Django 5.1 on 2024-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0004_remove_tournament_winner_tournament_historyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='invited_players',
            field=models.ManyToManyField(null=True, related_name='invited_players', to='matchmaking_app.matchuser'),
        ),
    ]
