# Generated by Django 5.1 on 2024-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_app', '0006_remove_matchuser_match_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='invited_players',
            field=models.ManyToManyField(related_name='invited_players', to='matchmaking_app.matchuser'),
        ),
    ]
