# Generated by Django 5.1 on 2024-10-29 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customuser_last_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_log',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 8, 0, 34, 668693, tzinfo=datetime.timezone.utc)),
        ),
    ]
