# Generated by Django 5.1 on 2024-10-29 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_customuser_last_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_log',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
