# Generated by Django 5.1 on 2024-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_creator', models.CharField(max_length=100)),
                ('game_id', models.CharField(max_length=100)),
            ],
        ),
    ]
