# Generated by Django 5.1 on 2024-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgame',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
