# Generated by Django 5.1 on 2024-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('player_1_name', models.CharField(max_length=100)),
                ('player_2_name', models.CharField(max_length=100)),
                ('player_1_connected', models.BooleanField(default=False)),
                ('player_2_connected', models.BooleanField(default=False)),
            ],
        ),
    ]
